---
# tasks file for myvhost

  - name: 패키지 설치 - httpd
    yum:
      name: httpd
      state: latest

  - name: 서비스 기동 - httpd
    service:
      name: httpd
      state: started
      enabled: yes
  
  - name: 서비스 설정 - vhost.conf
    template:
      src: vhost.conf.j2
      dest: /etc/httpd/conf.d/vhost.conf
      owner: root
      group: root
      mode: '0644'
    notify:
      - restart httpd

  - name: 디렉토리 생성 - "/var/www/vhosts/{{ ansible_hostname}}"
    file:
      path: "/var/www/vhosts/{{ ansible_hostname}}"
      state: directory
    
  - name: 파일 생성 - /var/www/vhosts/{{ ansible_hostname}}/index.html
    copy:
      content: " 내 서버에 어서왕 - ansible1 \n"
      dest: /var/www/vhosts/{{ ansible_hostname}}/index.html

  - name: 방화벽 설정 - http
    firewalld:
      service: http
      permanent: yes
      immediate: yes
      state: enabled