---
- name: 팩트 파일 생성
  hosts: webserver
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
      # 1. /etc/ansible/facts.d/ 디렉토리 생성
      # 2. custom.fact 파일 배포

    - name: create {{ remote_dir }} directory
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
        
      # 2. custom.fact 파일 배포
    - name: custom.fact 파일 배포
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
