---
- name: lamp 설치 및 기본 설정
  hosts: lamp
  vars:
    firewall: firewalld
  tasks:
    - name: 변수 포함
      include_vars: vars/main.yml

    - name: 테스크 포함
      include_tasks: tasks/main.yml
    
    - name: 최신버전의 firewalld 패키지 설치
      yum:
        name: "{{ firewall }}"
        state: latest
    
    - name: 방화벽 서비스 기동
      service:
        name: "{{ firewall }}"
        state: started
        enabled: true

    - name: 웹서버 포트 개방
      firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true
   
    - name: /var/www/html/index.html 파일 생성
      copy:
        content: "{{ ansible_fqdn }}({{ ansible_default_ipv4.address }}) has been customized by Ansible\n"
        dest: "{{ web_root }}/index.html"
        