---
- name: 플레이북 복구
  hosts: web1
  tasks:
# 1. 방화벽 닫기 - httpd
# 2. 서비스 내리기 - firewalld httpd
# 3. 웹서비스 설정 삭제 - var/www/html/index.html
# 4. 패키지 삭제 - httpd firewall
# 5. 팩트 삭제 - /etc/ansible/fact.d/
    - name: 테스크 포함
      include_tasks: tasks/restore_main.yml
      

