---
- name: 사용자 정의 팩트 배포
  hosts: web1
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: files/custom.fact
  tasks:
    # 1. 디렉토리 생성 /etc/ansible/fact.d
    # 2. 팩트 파일 배포
    # * files/custom.fact -> 각 관리 대상 호스트의 새 생성 디렉토리에!

    - name: 디렉토리 생성 /etc/ansible/fact.d
      file:
        path: "{{ remote_dir }}"
        state: directory
        mode: '0755'

    - name: 팩트 파일 배포
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
        


