---
- name: 하드웨어 정보 수집
  hosts: all
  gather_facts: yes
  vars:
    hwreport: hwreport.txt
  tasks:
    # 1. 파일 배포
    # 2. 수집된 팩트 정보를 가지고 hwreport.txt 파일 업데이트
    # * inventoryhostname
    # * totalmem
    # * sdasize
    # * biosversion
    # * hwreport.txt 수집
    - name: 파일 배포 {{ hwreport }}
      copy:
        src: "files/{{ hwreport }}"
        dest: "/root/{{ hwreport }}"
        owner: root
        group: root
        mode: '600'

    - name: inventoryhostname
      replace:
        path: "/root/{{ hwreport }}"
        regexp: 'inventoryhostname'
        replace: "{{ ansible_hostname }}"
    
    - name: totalmem
      replace:
        path: "/root/{{ hwreport }}"
        regexp: 'totalmem'
        replace: "{{ ansible_memtotal_mb }}"

    - name: biosversion
      replace:
        path: "/root/{{ hwreport }}"
        regexp: 'biosversion'
        replace: "{{ ansible_bios_version }}"

    - name: sdasize
      replace:
        path: "/root/{{ hwreport }}"
        regexp: 'sdasize'
        replace: "{{ ansible_devices.sda.size }}"

    # * hwreport.txt 수집
    - name: hwreport.txt 수집
      fetch:
        src: /root/{{ hwreport }}
        dest: "result/result-{{  inventory_hostname }}"
        flat: yes

        
