---
- name: https 서버 구축
  hosts: webservers
  gather_facts: yes
  vars_files: vars.yml 
  tasks:
    # 1. 체크 부분 = 배포판의 종류, 하드웨어 사양 점검
    - name: 1. 체크 부분 - 배포판의 종류, 하드웨어 사양 점검
      fail:
        msg: CentOS가 아니거나 또는 메모리가 부족 합니다
      when: (ansible_distribution != "CentOS") or (ansible_memtotal_mb < min_ram_mb)
    # 2. 패키지 설치 = httpd , mod_ssl, firewalld
    - name: 패키지 설치 = httpd , mod_ssl, firewalld
      yum:
        name: "{{ packages }}"
        state: latest
    # 3. 서비스 기동 = httpd, firewalld
    - name: 서비스 기동 = httpd, firewalld
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services }}"

    - name: block line
      block:
        # 4. 웹서비스 설정
        # 4.1.1. 디렉토리 생성 - /etc/pki/tls/{private,certs}
        - name: 디렉토리 생성 - /etc/pki/tls/{private,certs}
          file:
            path: "{{ item }}"
            state: directory
          with_items: "{{ ssl_dir }}"

        # 4.1.2. TLS 키 배포
        # * files/localhost.key -> /etc/pki/tls/private/localhost.key
        # * files/localhost.crt -> /etc/pki/tls/certs/localhost.crt
        - name: TLS 키 배포
          copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
          loop: "{{ web_config_files }}"
          notify: restart web service


        # 4.2. /var/www/html/index.html 파일 생성
        #   files/index.html -> /var/www/html/index.html
        - name: /var/www/html/index.html 파일 생성
          copy:
            src: "{{ ind_src }}"
            dest: "{{ ind_dest }}"


      rescue:
        - name: 설정 에러 메시지 출력
          debug:
            msg: |
              웹서버 설정 중 다음 한가지의 문제가 발생 하는것 같습니다.
              1) 인증서 디렉토리 실패
              2) 인증서 복사 실패
              3) 인덱스 파일 생성 실패


    # 5. 방화벽 등록 - http, https
    - name: 방화벽 등록 - http, https
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      with_items: "{{ fw_web }}"
    # -> 반드시 notify 사용
    # -> 반드시 block, rescue 문 사용
  
  
  handlers:
    - name: restart web service
      service:
        name: "{{ svc_web }}"
        state: restarted


    
