---
- name: 웹 서버 통합 설정
  hosts: webservers
  tasks:
#1) 웹 패키지 설치 및 기동
# httpd 패키지 설치 
#*httpd 서비스 기동
#2) 웹 서비스 설정 작업: /var/www/html/index.html
#3) 방화벽 패키지 설치 및 기동, 서비스 등록
#firewalld 패키지 설치
#firewalld 서비스 기동
#방화벽 서비스 등록 - http, https
#4) 클라이언트에서 웹 요청 테스트
#import_playbook 사용
# * import_tasks, include_tasks 사용 1

  - name: 웹 패키지 설치 및 기동  (tasks/environment.yml)
    include_tasks: tasks/environment.yml
    vars:
        package: httpd
        service: httpd
    when: ansible_os_family == 'RedHat'

  - name: 웹 서비스 설정 작업 /var/www/html/index.html
    import_tasks: tasks/placeholder.yml
    vars:
      file: /var/www/html/index.html
  
  - name: 방화벽 패키지 설치 및 기동, 서비스 등록 - {{ firewall_pkg }}
    import_tasks: tasks/firewall.yml
    vars:
      firewall_pkg: firewalld
      firewall_svc: firewalld
      rule:
        - http
        - https
- name: Import test play file and set the variable
  import_playbook: plays/test.yml
  vars:
    url: "http://ansible1.example.com"
   