---
- name: 방화벽 웹서버 설정
  hosts: all
  gather_facts: no
  tasks:
    # 1. 패키치 설치 : httpd, mod_ssl, firewalld
    # 2. 서비스 설정 : /var/www/html/index.html
    # 3. 서비스 기동 : httpd, firewalld
    # 4. 방화벽 기동 : http, https
    - name: 패키지 설치 - httpd, mod_ssl, firewalld
      yum:
        name: 
        - httpd
        - mod_ssl
        - firewalld
        state: latest
    
    - name: 서비스 설정 - /var/www/html/index.html
      copy:
        content: '</h1>웹서버 테스트 페이지 입니다!</h1>'
        dest: /var/www/html/index.html

    - name: 서비스 기동 - httpd, firewalld
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd
        - firewalld

    - name: 방화벽 기동 - http, https
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - http
        - https
      
