---
- name: 아파치 HTTPD 서비스 해제 (원복과정)
  hosts: all
  tasks:
    # (1) 방화벽 해제(http, https) 
    # (2) 서비스 비활성화(httpd, firewalld)
    # (3) 서비스 설정파일 삭제(/var/www/html/index.html)
    # (4) 패키지 삭제(httpd, mod_ssl, firewalld, python3-PyMySQL)
    
    # 실행 시, anp restore_factcheck.yml -i inventory1,2

    # (1) 방화벽 해제(http, https)
    - name: 방화벽 해제
      firewalld:
        service: "{{ item }}"
        permanent: no
        immediate: no
        state: disabled
      loop:
        - http
        - https
      
    # (2) 서비스 비활성화(httpd, firewalld)
    - name: 서비스 비활성화 httpd, firewalld
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - httpd
        - firewalld

    # (3) 서비스 설정파일 삭제(/var/www/html/index.html)
    - name: 서비스 설정파일 삭제 (/var/www/html/index.html)
      file:
        path: /var/www/html/index.html
        state: absent
  
    # (4) 패키지 삭제(httpd, mod_ssl, firewalld, python3-PyMySQL)
    - name: 1) 패키지 삭제 - httpd, mod_ssl, firewalld
      yum: 
        name:
          - httpd
          - mod_ssl
          - firewalld
        state: absent