---
- name: Restore the web-db service
  hosts: all
  tasks:
    # 1. 방화벽 내리기 - http, https
    # 2. 웹 서비스 설정 파일 삭제 - /var/www/html/index.php
    # 3. 서비스 비활성화 - httpd, mariadb
    # 4. 패키지 삭제 - web(httpd,php,php-mysql, php-pdo),db(mariadb-server), firewall(firewalld)

    - name: 1. 방화벽 내리기 - http, https
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      ignore_errors: yes
      loop:
        - http
        - https
    
    - name: 2. 웹 서비스 설정 파일 삭제 - /var/www/html/index.php
      file:
        path: /var/www/html/index.php
        state: absent
    
    - name: 3. 서비스 비활성화 - httpd, mariadb
      service:
        name: "{{ item }}"
        state: started
        enabled: no
      ignore_errors: yes
      loop:
        - httpd
        - mariadb
    - name: 4. 패키지 삭제
      yum:
        name:
          - httpd
          - mod_ssl
          - php
          - php-mysqlnd
          - php-pdo
          - mariadb-server
          - firewalld
        state: absent

