---
- name: web-db service
  hosts: web1
  tasks:
    # (1) 패키지 설치 - web(httpd,php,php-mysql, php-pdo),db(mariadb-server), firewall(firewalld)
    # (2) 웹서비스 설정 작업 - /var/www/html/index.php 생성
    # (3) 서비스 별 enable - firewall, web, db
    # (4) 방화벽 서비스 허용 - http,https 
    - name: 패키지 설치 - web(httpd,php,php-mysql, php-pdo),db(mariadb-server), firewall(firewalld)
      yum:
        name:
        - httpd
        - php
        - php-mysqlnd
        - php-pdo
        - mariadb-server
        - firewalld
        state: latest

    - name: 웹서비스 설정 작업 - /var/www/html/index.php 생성
      get_url:
        url: http://192.168.10.10/index.php
        dest: /var/www/html/index.php
    
    - name: 서비스 별 enable - firewall, web, db
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - firewalld
        - httpd
        - mariadb

    - name: 방화벽 서비스 허용 - http,https 
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - http
        - https
    
- name: 웹서버 테스트
  hosts: localhost
  tasks:
    - name: 인터넷 웹서버 연결 작업
      uri:
        url: http://web1.example.com
        return_content: yes
        status_code: 200



