- name: 사용자 추가
  hosts: all
  vars_files: secret2.yml
  tasks:
    - name: user1 add 
      user: 
        name: "{{ username }}"
        password: "{{ pwhash | password_hash('sha512') }}"

    - name: /etc/sudoers.d/devops 파일추가
      copy:
        src: files/devops
        dest: /etc/sudoers.d/devops
        owner: root
        group: root
        mode: '0440'

    - name: $HOME/.ssh/authorized_keys 내용추가
      authorized_key:
        user: devops
        state: present
        key: "{{ item }}"
      with_file:
        - ~/.ssh/id_rsa.pub
      