---
- name: 사용자 추가 
  hosts: devservers
  remote_user: devops
  become: true
  vars_files:
    - vars/secret.yml
  tasks:
    - name: secret.yml 파일을 가지고 사용자 추가
      user:
        name: "{{  item.name }}"
        password: "{{ item.pw | password_hash('sha512') }}"
      with_items: "{{ newusers }}"