---
# anp --vault-password-file=vault-pass restore_createuser.yml 

- name: 사용자 제거
  hosts: devservers
  remote_user: devops
  become: true
  vars_files:
    - vars/secret.yml
  tasks:
    - name: secret.yml 파일을 가지고 사용자 제거
      user:
        name: "{{  item.name }}"
        state: absent
        remove: yes
      with_items: "{{ newusers }}"