---
- name: 1st play
  hosts: web1
  tasks:
    - name: 패키지 설치 - httpd, mod_ssl, firewalld
      yum:
        name: 
          - httpd
          - firewalld
          - mod_ssl
        state: latest
    - name: 웹서버 설정
      copy:
        content: "제 서버에 어서오세요!\n"
        dest: /var/www/html/index.html
    - name: 서비스 설정 - httpd, firewalld
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd
        - firewalld
    - name: 방화벽 설정 - http, https
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - http
        - https

- name: 2st play
  hosts: localhost
  tasks:
    - name: 웹페이지1 테스트 해보기
      uri:
        url: http://web1.example.com
        return_content: yes
        status_code: 200
 #     register: output
 #   - debug: var=output





