---
- name: 아파치 HTTPD 서비스 기동
  hosts: webserver
  vars_files: vars/vars.yml
  tasks:
    # (ㄱ) 패키지 설치(httpd, mod_ssl, firewalld, python3-PyMySQL)
    # (ㄴ) 서비스 설정(/var/www/html/index.html)
    # (ㄷ) 서비스 기동(httpd, firewalld)
    # (ㄹ) 방화벽 등록(http, https)

    # (ㄱ) 패키지 설치(httpd, mod_ssl, firewalld, python3-PyMySQL)
    - name: 1) 패키지 설치 - {{ pkg_http }}, {{ pkg_https }}, {{ pkg_python }}, {{ pkg_fw }}
      yum: 
        name:
          - "{{ pkg_http }}" 
          - "{{ pkg_https }}"
          - "{{ pkg_python }}"
          - "{{ pkg_fw }}"
        state: present

    # (ㄴ) 서비스 설정(/var/www/html/index.html)
    - name: 2) 서비스 설정
      copy:
        content: '</h1>웹서버 테스트 페이지 입니다!</h1>'
        dest: /var/www/html/index.html

    # (ㄷ) 서비스 기동(httpd, firewalld)
    - name: 서비스 기동 {{ svc_fw }}, {{ svc_web }}
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - "{{ svc_fw  }}"
        - "{{ svc_web }}"

    # (ㄹ) 방화벽 등록(http, https)
    - name: 방화벽 등록 - {{ fw_http }}, {{ fw_https }}
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - "{{ fw_http }}"
        - "{{ fw_https }}" 




- name: 웹서버 확인
  hosts: localhost
  tasks:
    - name: 웹 페이지 확인
      uri:
        url: http://web1.example.com
        return_content: yes
        status_code: 200
      register: output
    - debug: var=output
