---
- name: 아파치 HTTPD 서비스 해제 (원복과정)
  hosts: webserver
  vars_files: vars/vars.yml
  tasks:
    # (1) 방화벽 해제(http, https) 
    # (2) 서비스 비활성화(httpd, firewalld)
    # (3) 서비스 설정파일 삭제(/var/www/html/index.html)
    # (4) 패키지 삭제(httpd, mod_ssl, firewalld, python3-PyMySQL)
    
    # (1) 방화벽 해제(http, https)
    - name: 방화벽 해제 - {{ fw_http }}, {{ fw_https }}
      firewalld:
        service: "{{ item }}"
        permanent: no
        immediate: no
        state: disabled
      ignore_errors: yes
      loop:
        - "{{ fw_http }}"
        - "{{ fw_https }}" 
      
    # (2) 서비스 비활성화(httpd, firewalld)
    - name: 서비스 비활성화 {{ svc_fw }}, {{ svc_web }}
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - "{{ svc_fw  }}"
        - "{{ svc_web }}"

    # (3) 서비스 설정파일 삭제(/var/www/html/index.html)
    - name: 서비스 설정파일 삭제 (/var/www/html/index.html)
      file:
        path: /var/www/html/index.html
        state: absent
  
    # (4) 패키지 삭제(httpd, mod_ssl, firewalld, python3-PyMySQL)
    - name: 1) 패키지 삭제 - {{ pkg_http }}, {{ pkg_https }}, {{ pkg_python }}, {{ pkg_fw }}
      yum: 
        name:
          - "{{ pkg_http }}" 
          - "{{ pkg_https }}"
          - "{{ pkg_python }}"
          - "{{ pkg_fw }}"
        state: absent
      
