---
# 1. 방화벽 닫기 - httpd
# 2. 서비스 내리기 - firewalld httpd
# 3. 웹서비스 설정 삭제 - var/www/html/index.html
# 4. 패키지 삭제 - httpd firewall
# 5. 팩트 삭제 - /etc/ansible/fact.d/
  - name: 1. 방화벽 닫기 - httpd
    firewalld:
      service: httpd
      state: disabled
      permanent: yes
    ignore_errors: yes
    
  - name: 2. 서비스 내리기 - firewalld httpd
    service:
      name: "{{ item }}"
      state: stopped
    ignore_errors: yes
    loop:
      - firewalld
      - httpd
      - mariadb-server
      
  - name: 3. 웹서비스 설정 삭제 - var/www/html/index.html
    file: 
      path: var/www/html/index.html
      state: absent

  - name: 4. 패키지 삭제 - httpd firewall
    yum:
      name: "{{ item }}"
      state: absent
    loop:
      - httpd
      - firewalld
      - mariadb

  - name: 5. 팩트 삭제 - /etc/ansible/facts.d/
    file: 
      path: /etc/ansible/facts.d
      state: absent

  