---
- name: /etc/motd 설정
  hosts: all
  gather_facts: true
  vars:
    system_owner: webmaster@example.com
  tasks:
    - name: deploy /etc/motd (파일 배포)
      template:
        src: template/motd.j2
        dest: /etc/motd
        


