---
- name: mariadb 서버 기동
  hosts: database_prod
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL
    mariadb_service: mariadb

  tasks:
    # 1. 패키지 설치 - mariadb-server, python-PyMySQL
    - name: 1. 패키지 설치 - mariadb-server, python-PyMySQL
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ mariadb_packages }}"
      when: ansible_distribution == 'CentOS'


    # 2. 서비스 기동
    - name: 2. 서비스 기동
      service:
        name: "{{ mariadb_service }}"
        state: started

